### ISSUE TITLE
One vagrantfile to run whole stack with "infra" apps

### ISSUE THREAD

**Issue by rasheedamir** [stakater/bugs#110]
Create a vagrantfile which starts just ONE virtual machine and it should autoconfigure following infra apps:

1. Consul
2. ELK
3. extendable so, its easy to add more ( e.g. Kafka, Nexus, etc. )

It should be easy to add or remove the apps; in case someone has a machine with lower RAM it can just run as few as required.

Everything should be based on auto discovery!

Best if we can have just ONE vagrantfile and user can select either to run the stack on "VirtualBox" or "AWS".

**Comment by rasheedamir** [comment]
I think we should run ETCD & CONSUL on one really small & nano instance. As it is something which is required 24x7?

**Comment by rasheedamir** [comment]
To match production topology we should run them on separate instances. So, we might end up with 2 vagrantfiles.

**Comment by hazim1093** [comment]
The "Developer Environment" repository serves this purpose.
https://github.com/stakater/developer-environment
