### ISSUE TITLE
Docker Images not found in AMI when Docker data is on EBS Device

### ISSUE THREAD

**Issue by hazim1093** [stakater/bugs#13]
EBS Devices in AMI:
EBS devices data, (docker images) not found in instances created from AMI. Reason: We keep docker data on a separate EBS device. EBS devices are not a part of the AMI so the docker data is not included in the AMI.

Solution tried: 
Taking snapshot of the EBS device of base instance, and adding an EBS device with AMI configuration so that all instances have an EBS device made from that snapshot.Issue: Base instance and AMI have same cloud config, The ebs device is formatted in the cloud config in order to mount it to docker data. After creation of instance from AMI, the ebs device is formatted again, as it uses the same config, so there is no docker data in instances from AMI.

Workaround: 
Don’t mount ebs to docker data in prod, use root device for docker in prod

**Comment by rasheedamir** [comment]
@hazim1093 this seems to be irrelevant now? As now are always going to use root devices on the instances for docker data? Right? Maybe we can close it as won't fix?

**Comment by hazim1093** [comment]
Yes it is irrelevant now, due to our current approach, closing.
