### ISSUE TITLE
Change GoCD config to json format to support git versioning of GoCD Config

### ISSUE THREAD

**Issue by hazim1093** [stakater/bugs#14]
Change config to json or yaml format to support feature to use config repo(git). (Gocd 16.7.0+) (low priority)

**Comment by rasheedamir** [comment]
the main purpose of this one will be "pipeline as code"

**Comment by hazim1093** [comment]
We've updated GoCD to 17.4.0 and are using the YAML plugin: 
https://github.com/tomzo/gocd-yaml-config-plugin

Sample config can be found here: 
https://github.com/stakater/java-test-app-ci-and-versioning/blob/master/ci.gocd.yaml
