### ISSUE TITLE
Cleanup AMIs

### ISSUE THREAD

**Issue by hazim1093** [stakater/bugs#18]
Create a pipeline to delete old AMIs from AWS. (Possible through aws cli)
* Scheduled pipeline
* Define delete old AMIs criteria e.g. month old AMIs or etc

**Comment by hazim1093** [comment]
Also add documentation in the documentation repo, on how to use the delete AMI pipeline and how it can be customized.

**Comment by hamza3202** [comment]
We decided to only keep three AMI's at most for each app in each environment: 
1- The most recently created AMI.
2- The AMI deployed on Blue group instance.
3- The AMI deployed on Green group instance.

After each AMI creation we have a new AMI  deletion stage which deletes the AMIs.
We only need to give it the Application Name with -a flag and Environment with -e flag

**Comment by hamza3202** [comment]
will  be resolved with pull request:
https://github.com/stakater/infrastructure-reference/pull/37

**Comment by hamza3202** [comment]
update: we need to delete snapshots as well

**Comment by hamza3202** [comment]
resolved with pull request: 
https://github.com/stakater/infrastructure-reference/pull/40
