### ISSUE TITLE
Create pipeline to destroy production infrastructure

### ISSUE THREAD

**Issue by hazim1093** [stakater/bugs#20]
Create pipeline to destroy production infrastructure created from gocd

**Comment by rasheedamir** [comment]
@hazim1093 what is need of this?

**Comment by hazim1093** [comment]
you cannot destroy the Prod infrastructure from your local stakater setup as you destroy the rest of the stack. 

There are two options: 
1. destroy it from gocd, i.e. from where it was created. 
2. Pull the prod deployment reference code, set it up (variable values etc) then destroy it.

If prod blue-green infra is not destroyed, you would not be able to destroy the rest of prod infra from the local stakater set up

**Comment by rasheedamir** [comment]
OK so, its a dependency.

**Comment by hamza3202** [comment]
Resolved with pull request:
https://github.com/stakater/infrastructure-reference/pull/36
