### ISSUE TITLE
Update prod ssl certificate variable flow

### ISSUE THREAD

**Issue by hazim1093** [stakater/bugs#30]
Currently, The SSL certificate ARN (from AWS certificate manager), has to be stored in a file at a specific location on the GoCD Server. 

Update the scripts and cruise-config.xml file so that the certificate ARN is passed as a variable from GoCD instead of from the file

**Comment by rasheedamir** [comment]
@hazim1093 can you please add more details to this ticket?

**Comment by hazim1093** [comment]
@ozairaurora  also rename the "INTERNAL_SUPPORT" variable (Used to mark an elb as internal) to something more meaningful, along side this ticket.

**Comment by rasheedamir** [comment]
@hazim1093 @ozairaurora what is the status of this blocker?

**Comment by ozairaurora** [comment]
@rasheedamir Haven't started it, I'll do it today with the help of @hazim1093 and will update you.
