### ISSUE TITLE
Scheduled start & stop of EC2 instances

### ISSUE THREAD

**Issue by rasheedamir** [stakater/bugs#37]
For economic reason, the non-prod instances should be running only during a specified time window. And it should happen automatically.

Keeping an instance running 24/7 when it isn’t actually being utilized is consuming unnecessary resources. Turning off instances when they won’t be utilized eliminates this resource wastage, and reduces cost. Fortunately, EC2 has a powerful set of tools that makes that very easy to configure schedules for turning instances on and off, and re-assigning static IP addresses.

**Comment by hazim1093** [comment]
@rasheedamir is this resolved via https://github.com/stakater/bugs/issues/67 ?

**Comment by hazim1093** [comment]
Duplicate of https://github.com/stakater/bugs/issues/67
