### ISSUE TITLE
Etcd's initial cluster file is not uploaded upon recreation

### ISSUE THREAD

**Issue by hamza3202** [stakater/bugs#38]
if etcd gets destroyed or restarted (need to make sure) then its initial cluster file is not updated on the s3 bucket

**Comment by rasheedamir** [comment]
@hamza3202 then how did you work around it?

**Comment by hamza3202** [comment]
@rasheedamir We manually updated the file on s3 bucket

**Comment by rasheedamir** [comment]
@hamza3202 what do you mean by recreation?

**Comment by hamza3202** [comment]
@rasheedamir sorry i meant recreated but we need to make sure of it once more

**Comment by hazim1093** [comment]
@hamza3202 The bucket url currently being sent to the docker image that generates etcd peer files is like `s3-<region>://<bucket-name>`. ( etcd-init.sh in ETCD cloud init yaml file)

I'm not sure if region is allowed in this type of s3 URL, but I don't think we need to specify region here as the docker images used to generate and upload peer files already specifies region separately. 

This *MIGHT* be the cause for it to not upload/update files on S3 

Reference: 
https://github.com/dockerage/etcd-aws-cluster/blob/master/etcd-aws-proxy#L27

**Comment by hamza3202** [comment]
@hazim1093 yes you were right. This was the issue and its fixed now
