### ISSUE TITLE
Review EBS usage to optimize infrastructure cost

### ISSUE THREAD

**Issue by rasheedamir** [stakater/bugs#43]
Review the EBS usage; and we should make its use optional; do we really need to attach EBS to each machine?

When and why should we attach EBS?

**Comment by rasheedamir** [comment]
As discussed we shouldn't attach any EBS by default to any instance.

**Comment by hamza3202** [comment]
fixed in the following pull requests
https://github.com/stakater/ami-baker/pull/1#pullrequestreview-14554627
https://github.com/stakater/prod-deployment-reference/pull/11#event-906463923
https://github.com/stakater/infrastructure-reference/pull/35#event-906463670
