### ISSUE TITLE
Add repos of vagrant machines with ELK and Etcd running on coreos

### ISSUE THREAD

**Issue by hazim1093** [stakater/bugs#54]
Add repos of vagrant machines with ELK and Etcd running on Coreos, and service discovery performed through Consul

**Comment by hazim1093** [comment]
Done https://github.com/stakater/coreos-vagrant-with-consul-elk

**Comment by rasheedamir** [comment]
Excellent @hazim1093 you removed config.rb; any specific reason for it? how does etcd generates new token then?

**Comment by hazim1093** [comment]
@rasheedamir, we don't use public etcd discovery. So we don't need the token
