### ISSUE TITLE
Automatically shutdown down instances

### ISSUE THREAD

**Issue by rasheedamir** [stakater/bugs#67]
A feature should be given so, that its possible to shutdown and restart the instances which are not required to be running always e.g. 

* gocd machine can be stopped on weekends and after working hours

It should be done in a configurable way;

Couple of solutions have been discussed here and the last one seems to be the best. It will lock us to AWS for this feature but its most cost efficient.
https://blog.goodmirek.com/periodically-start-and-stop-ec2-instance-bf25c01e68f1#.4rpp9aouq

One possible solution can be is to use AWS Lambda; and write a function which reads a file from s3 bucket which contains an instance tag ( e.g. gocd ) and cron pattern; which is run periodically at scheduled times.
OR just run a nano instance in global admiral which has script and does a similiar thing.

**Comment by rasheedamir** [comment]
duplicate #37

**Comment by hamza3202** [comment]
We have decided to use nano instance as lambda would require cloud watch as well and we will have to manage multiple resources and then there is the cost factor as well

**Comment by hamza3202** [comment]
resolved with pull-request:
https://github.com/stakater/infrastructure-reference/pull/39

and new repository 
https://github.com/stakater/house-keeper

**Comment by hazim1093** [comment]
Autoscaling group properties should be enabled after ALL instances in the group have been started.

**Comment by hamza3202** [comment]
also if region is specified in command then instance should execute command for that region

**Comment by hamza3202** [comment]
Fixed in pull-request 
https://github.com/stakater/house-keeper/pull/1
