### ISSUE TITLE
EFS not mounted before application start

### ISSUE THREAD

**Issue by hazim1093** [stakater/bugs#70]
Facing this issue again, our stack is not ensuring that the application must start after EFS has been mounted. 

This behavior is observed only when starting `stopped` instances. 

NOTE: We have already added `Requires` dependency for EFS mounting service in application's systemd unit. 

I think the application unit starts after the EFS mounting service as expected, but does not wait for EFS to be actually mounted.

**Comment by hamza3202** [comment]
The same needs to be managed on the mysql instance as well

**Comment by hamza3202** [comment]
The issue was with the order of dependency, If you add dependencies in this order then it mounts properly
Requires=runcmd.service
After=runcmd.service

**Comment by hamza3202** [comment]
Documented with following pull request
https://github.com/stakater/documentation/pull/5
